// ACCOUNT
export const CREATE_ACCOUNT_START = "CREATE_ACCOUNT_START";
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CREATE_ACCOUNT_ERROR = "CREATE_ACCOUNT_ERROR";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

// MENUS
export const GET_MENUS_START = "GET_MENUS_START";
export const GET_MENUS_SUCCESS = "GET_MENUS_SUCCESS";
export const GET_MENUS_ERROR = "GET_MENUS_ERROR";

export const CREATE_MENU_SUCCESS = "CREATE_MENU_SUCCESS";
export const CREATE_MENU_START = "CREATE_MENU_START";
export const CREATE_MENU_ERROR = "CREATE_MENU_ERROR";
export const DELETE_MENU_SUCCESS = "DELETE_MENU_SUCCESS";

export const UPDATE_MENU_SUCCESS = "UPDATE_MENU_SUCCESS";

// CHOICES
export const CREATE_CHOICE_SUCCESS = "CREATE_CHOICE_SUCCESS";
export const CREATE_CHOICE_ERROR = "CREATE_CHOICE_ERROR";
export const CREATE_CHOICE_START = "CREATE_CHOICE_START";

export const GET_CHOICES_START = "GET_CHOICES_START";
export const GET_CHOICES_ERROR = "GET_CHOICES_ERROR";
export const GET_CHOICES_SUCCESS = "GET_CHOICES_SUCCESS";

export const GET_ONE_CHOICE_SUCCESS = "GET_ONE_CHOICE_SUCCESS";

export const DELETE_CHOICE_SUCCESS = "DELETE_CHOICE_SUCCESS";

export const UPDATE_CHOICE_SUCCESS = "UPDATE_CHOICE_SUCCESS";
